const actions = {
  SET_STATE: 'friends/SET_STATE',
  GET_FRIENDS: 'friends/GET_FRIENDS',
  GET_FRIEND_REQUEST: 'friends/GET_FRIEND_REQUEST',
  SEND_FRIEND_REQUEST: 'friends/SEND_FRIEND_REQUEST',
  UPDATE_FRIEND_REQUEST: 'friends/UPDATE_FRIEND_REQUEST',
  UPDATE_REQUEST_SENT: 'friends/UPDATE_REQUEST_SENT',
  ACCEPT_FRIEND_REQUEST: 'friends/ACCEPT_FRIEND_REQUEST',
  REJECT_FRIEND_REQUEST: 'friends/REJECT_FRIEND_REQUEST',
  CANCEL_REQUEST: 'friends/CANCEL_REQUEST',
}

export default actions