const actions = {
  SET_STATE: 'conversations/SET_STATE',
  GET_CONVERSATIONS: 'conversations/GET_CONVERSATIONS',
  CREATE_CONVERSATION: 'conversations/CREATE_CONVERSATION',
  ADD_USER_CONVERSATION: 'conversations/ADD_USER_CONVERSATION',
  REMOVE_USER_CONVERSATION: 'conversations/REMOVE_USER_CONVERSATION',
  UPDATE_CONVERSATION: 'conversations/UPDATE_CONVERSATION',
  CHECK_CONVERSATION_EXIST: 'conversations/CHECK_CONVERSATION_EXIST',
}

export default actions