const actions = {
  SET_STATE: 'conversations/SET_STATE',
  GET_CONVERSATIONS: 'conversations/GET_CONVERSATIONS',
  CREATE_CONVERSATION: 'conversations/CREATE_CONVERSATION',
  ADD_USER_CONVERSATION: 'conversations/ADD_USER_CONVERSATION',
  REMOVE_USER_CONVERSATION: 'conversations/REMOVE_USER_CONVERSATION',
  UPDATE_CONVERSATION: 'conversations/UPDATE_CONVERSATION',
  CHECK_CONVERSATION_EXIST: 'conversations/CHECK_CONVERSATION_EXIST',
  UPDATE_CONVERSATION_NAME: 'conversations/UPDATE_CONVERSATION_NAME',
  GET_CONVERSATION_BY_ID: 'conversations/GET_CONVERSATION_BY_ID',
  SET_SELECTED_STATE: 'conversations/SET_SELECTED_STATE',
}

export default actions